/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
    InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
    LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
    MediaCard: typeof import('./src/components/media/MediaCard.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
    SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TContent: typeof import('tdesign-vue-next')['Content']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLink: typeof import('tdesign-vue-next')['Link']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTag: typeof import('tdesign-vue-next')['Tag']
  }
}

// For TSX support
declare global {
  const EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
  const InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
  const LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
  const MediaCard: typeof import('./src/components/media/MediaCard.vue')['default']
  const PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
  const SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const THeader: typeof import('tdesign-vue-next')['Header']
  const THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
  const TIcon: typeof import('tdesign-vue-next')['Icon']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TLink: typeof import('tdesign-vue-next')['Link']
  const TList: typeof import('tdesign-vue-next')['List']
  const TListItem: typeof import('tdesign-vue-next')['ListItem']
  const TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
  const TLoading: typeof import('tdesign-vue-next')['Loading']
  const TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
  const TPagination: typeof import('tdesign-vue-next')['Pagination']
  const TSpace: typeof import('tdesign-vue-next')['Space']
  const TTag: typeof import('tdesign-vue-next')['Tag']
}