/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtPlayer: typeof import('./src/components/VideoPlayer/ArtPlayer.vue')['default']
    EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
    InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
    LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
    MainLayout: typeof import('./src/components/PageLayout/MainLayout.vue')['default']
    MpvPlayer: typeof import('./src/components/VideoPlayer/MpvPlayer.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
    PlayerSlider: typeof import('./src/components/common/PlayerSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
    SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TBackTop: typeof import('tdesign-vue-next')['BackTop']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TContent: typeof import('tdesign-vue-next')['Content']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TParagraph: typeof import('tdesign-vue-next')['Paragraph']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    WindowControl: typeof import('./src/components/WindowControl/WindowControl.vue')['default']
  }
}

// For TSX support
declare global {
  const ArtPlayer: typeof import('./src/components/VideoPlayer/ArtPlayer.vue')['default']
  const EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
  const InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
  const LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
  const MainLayout: typeof import('./src/components/PageLayout/MainLayout.vue')['default']
  const MpvPlayer: typeof import('./src/components/VideoPlayer/MpvPlayer.vue')['default']
  const PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
  const PlayerSlider: typeof import('./src/components/common/PlayerSlider.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
  const SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
  const TAside: typeof import('tdesign-vue-next')['Aside']
  const TBackTop: typeof import('tdesign-vue-next')['BackTop']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TCard: typeof import('tdesign-vue-next')['Card']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const TForm: typeof import('tdesign-vue-next')['Form']
  const TFormItem: typeof import('tdesign-vue-next')['FormItem']
  const THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
  const TIcon: typeof import('tdesign-vue-next')['Icon']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TLoading: typeof import('tdesign-vue-next')['Loading']
  const TMenu: typeof import('tdesign-vue-next')['Menu']
  const TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
  const TParagraph: typeof import('tdesign-vue-next')['Paragraph']
  const TRadio: typeof import('tdesign-vue-next')['Radio']
  const TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
  const TSelect: typeof import('tdesign-vue-next')['Select']
  const TSlider: typeof import('tdesign-vue-next')['Slider']
  const TSubmenu: typeof import('tdesign-vue-next')['Submenu']
  const TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
  const TTabs: typeof import('tdesign-vue-next')['Tabs']
  const TTag: typeof import('tdesign-vue-next')['Tag']
  const TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  const WindowControl: typeof import('./src/components/WindowControl/WindowControl.vue')['default']
}