/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToolBack: typeof import('./src/components/PageLayout/AppToolBack.vue')['default']
    AppToolLayout: typeof import('./src/components/PageLayout/AppToolLayout.vue')['default']
    ArtPlayer: typeof import('./src/components/VideoPlayer/ArtPlayer.vue')['default']
    ChatSender: typeof import('./src/components/ChatSender/ChatSender.vue')['default']
    CustomWebview: typeof import('./src/components/webview/CustomWebview.vue')['default']
    EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
    HorizontalSplitPanel: typeof import('./src/components/common/HorizontalSplitPanel.vue')['default']
    InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
    LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
    MainLayout: typeof import('./src/components/PageLayout/MainLayout.vue')['default']
    MarkdownEditor: typeof import('./src/components/common/MarkdownEditor.vue')['default']
    MarkdownPreview: typeof import('./src/components/common/MarkdownPreview.vue')['default']
    MonacoEditor: typeof import('./src/components/common/MonacoEditor.vue')['default']
    NetworkVideoCard: typeof import('./src/components/card/NetworkVideoCard.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
    PlayerSlider: typeof import('./src/components/common/PlayerSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
    SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
    TauriWebview: typeof import('./src/components/webview/TauriWebview.vue')['default']
    UtoolsWebview: typeof import('./src/components/webview/UtoolsWebview.vue')['default']
    VerticalSplitPanel: typeof import('./src/components/common/VerticalSplitPanel.vue')['default']
  }
}

// For TSX support
declare global {
  const AppToolBack: typeof import('./src/components/PageLayout/AppToolBack.vue')['default']
  const AppToolLayout: typeof import('./src/components/PageLayout/AppToolLayout.vue')['default']
  const ArtPlayer: typeof import('./src/components/VideoPlayer/ArtPlayer.vue')['default']
  const ChatSender: typeof import('./src/components/ChatSender/ChatSender.vue')['default']
  const CustomWebview: typeof import('./src/components/webview/CustomWebview.vue')['default']
  const EmptyResult: typeof import('./src/components/Result/EmptyResult.vue')['default']
  const HorizontalSplitPanel: typeof import('./src/components/common/HorizontalSplitPanel.vue')['default']
  const InfoResult: typeof import('./src/components/Result/InfoResult.vue')['default']
  const LoadingResult: typeof import('./src/components/Result/LoadingResult.vue')['default']
  const MainLayout: typeof import('./src/components/PageLayout/MainLayout.vue')['default']
  const MarkdownEditor: typeof import('./src/components/common/MarkdownEditor.vue')['default']
  const MarkdownPreview: typeof import('./src/components/common/MarkdownPreview.vue')['default']
  const MonacoEditor: typeof import('./src/components/common/MonacoEditor.vue')['default']
  const NetworkVideoCard: typeof import('./src/components/card/NetworkVideoCard.vue')['default']
  const PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
  const PlayerSlider: typeof import('./src/components/common/PlayerSlider.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
  const SuccessResult: typeof import('./src/components/Result/SuccessResult.vue')['default']
  const TauriWebview: typeof import('./src/components/webview/TauriWebview.vue')['default']
  const UtoolsWebview: typeof import('./src/components/webview/UtoolsWebview.vue')['default']
  const VerticalSplitPanel: typeof import('./src/components/common/VerticalSplitPanel.vue')['default']
}