import * as monaco from 'monaco-editor';

export const nginxLanguageConfiguration: monaco.languages.LanguageConfiguration = {
  comments: {
    lineComment: '#'
  },
  brackets: [
    ['{', '}'],
    ['[', ']'],
    ['(', ')']
  ],
  autoClosingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' },
    { open: "'", close: "'" }
  ],
  surroundingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' },
    { open: "'", close: "'" }
  ]
};

export const nginxKeywords = [
  'events',
  'http',
  'server',
  'location',
  'upstream',
  'listen',
  'server_name',
  'root',
  'index',
  'access_log',
  'error_log',
  'client_max_body_size',
  'proxy_pass',
  'proxy_set_header',
  'proxy_connect_timeout',
  'proxy_send_timeout',
  'proxy_read_timeout',
  'proxy_buffering',
  'proxy_cache',
  'proxy_cache_valid',
  'proxy_cache_path',
  'proxy_cache_key',
  'proxy_cache_bypass',
  'proxy_no_cache',
  'proxy_redirect',
  'proxy_http_version',
  'proxy_ssl_server_name',
  'proxy_ssl_protocols',
  'proxy_ssl_ciphers',
  'proxy_ssl_verify',
  'proxy_ssl_verify_depth',
  'proxy_ssl_trusted_certificate',
  'proxy_ssl_certificate',
  'proxy_ssl_certificate_key',
  'proxy_ssl_session_reuse',
  'proxy_ssl_name',
  'proxy_ssl_crl',
  'proxy_intercept_errors',
  'proxy_next_upstream',
  'proxy_next_upstream_tries',
  'proxy_next_upstream_timeout',
  'proxy_hide_header',
  'proxy_pass_header',
  'proxy_ignore_headers',
  'proxy_set_body',
  'proxy_method',
  'proxy_cookie_domain',
  'proxy_cookie_path',
  'proxy_force_ranges',
  'proxy_limit_rate',
  'proxy_request_buffering',
  'proxy_socket_keepalive',
  'proxy_timeout',
  'proxy_bind',
  'fastcgi_pass',
  'fastcgi_index',
  'fastcgi_param',
  'fastcgi_cache',
  'fastcgi_cache_path',
  'fastcgi_cache_key',
  'fastcgi_cache_valid',
  'fastcgi_cache_bypass',
  'fastcgi_no_cache',
  'fastcgi_hide_header',
  'fastcgi_pass_header',
  'fastcgi_ignore_headers',
  'fastcgi_connect_timeout',
  'fastcgi_send_timeout',
  'fastcgi_read_timeout',
  'fastcgi_buffer_size',
  'fastcgi_buffers',
  'fastcgi_busy_buffers_size',
  'fastcgi_temp_file_write_size',
  'fastcgi_intercept_errors',
  'uwsgi_pass',
  'uwsgi_param',
  'uwsgi_cache',
  'uwsgi_cache_path',
  'uwsgi_cache_key',
  'uwsgi_cache_valid',
  'uwsgi_cache_bypass',
  'uwsgi_no_cache',
  'uwsgi_connect_timeout',
  'uwsgi_send_timeout',
  'uwsgi_read_timeout',
  'uwsgi_buffer_size',
  'uwsgi_buffers',
  'uwsgi_busy_buffers_size',
  'uwsgi_temp_file_write_size',
  'uwsgi_intercept_errors',
  'scgi_pass',
  'scgi_param',
  'memcached_pass',
  'memcached_connect_timeout',
  'memcached_send_timeout',
  'memcached_read_timeout',
  'memcached_buffer_size',
  'memcached_next_upstream',
  'gzip',
  'gzip_vary',
  'gzip_proxied',
  'gzip_comp_level',
  'gzip_types',
  'gzip_disable',
  'gzip_min_length',
  'gzip_buffers',
  'gzip_http_version',
  'ssl',
  'ssl_certificate',
  'ssl_certificate_key',
  'ssl_protocols',
  'ssl_ciphers',
  'ssl_prefer_server_ciphers',
  'ssl_session_cache',
  'ssl_session_timeout',
  'ssl_session_tickets',
  'ssl_stapling',
  'ssl_stapling_verify',
  'ssl_trusted_certificate',
  'ssl_client_certificate',
  'ssl_verify_client',
  'ssl_verify_depth',
  'ssl_crl',
  'ssl_dhparam',
  'add_header',
  'expires',
  'try_files',
  'alias',
  'rewrite',
  'return',
  'internal',
  'break',
  'last',
  'redirect',
  'permanent',
  'if',
  'set',
  'default_type',
  'charset',
  'charset_types',
  'include',
  'worker_processes',
  'worker_connections',
  'worker_rlimit_nofile',
  'worker_rlimit_sigpending',
  'worker_shutdown_timeout',
  'multi_accept',
  'use',
  'daemon',
  'master_process',
  'pid',
  'error_log',
  'debug_connection',
  'env',
  'timer_resolution',
  'working_directory',
  'user',
  'group',
  'pcre_jit',
  'thread_pool',
  'thread_pool_size',
  'aio',
  'aio_write',
  'directio',
  'directio_alignment',
  'sendfile',
  'sendfile_max_chunk',
  'tcp_nopush',
  'tcp_nodelay',
  'reset_timedout_connection',
  'keepalive_timeout',
  'keepalive_requests',
  'lingering_time',
  'lingering_timeout',
  'satisfy',
  'satisfy_any',
  'auth_basic',
  'auth_basic_user_file',
  'auth_request',
  'auth_request_set',
  'deny',
  'allow',
  'limit_except',
  'limit_rate',
  'limit_rate_after',
  'limit_req',
  'limit_req_zone',
  'limit_req_status',
  'limit_conn',
  'limit_conn_zone',
  'limit_conn_status',
  'log_format',
  'log_not_found',
  'log_subrequest',
  'open_log_file_cache',
  'open_file_cache',
  'open_file_cache_valid',
  'open_file_cache_min_uses',
  'open_file_cache_errors',
  'recursive_error_pages',
  'server_tokens',
  'server_name_in_redirect',
  'port_in_redirect',
  'msie_padding',
  'msie_refresh',
  'absolute_redirect',
  'ignore_invalid_headers',
  'merge_slashes',
  'underscores_in_headers',
  'variables_hash_bucket_size',
  'variables_hash_max_size',
  'types_hash_bucket_size',
  'types_hash_max_size',
  'server_names_hash_bucket_size',
  'server_names_hash_max_size',
  'types',
  'default_type',
  'client_body_buffer_size',
  'client_body_in_file_only',
  'client_body_in_single_buffer',
  'client_body_timeout',
  'client_header_buffer_size',
  'client_header_timeout',
  'client_max_body_size',
  'large_client_header_buffers',
  'connection_pool_size',
  'request_pool_size',
  'postpone_output',
  'send_timeout',
  'subrequest_output_buffer_size',
  'tcp_nodelay',
  'tcp_nopush',
  'chunked_transfer_encoding',
  'etag',
  'if_modified_since',
  'max_ranges',
  'resolver',
  'resolver_timeout',
  'resolver_address',
  'valid_referers',
  'invalid_referers',
  'referer_hash_max_size',
  'referer_hash_bucket_size',
  'real_ip_header',
  'set_real_ip_from',
  'real_ip_recursive',
  'geo',
  'geoip_country',
  'geoip_city',
  'geoip_org',
  'geoip_proxy',
  'geoip_proxy_recursive',
  'map',
  'map_hash_bucket_size',
  'map_hash_max_size',
  'split_clients',
  'perl',
  'perl_modules',
  'perl_require',
  'perl_set',
  'image_filter',
  'image_filter_buffer',
  'image_filter_jpeg_quality',
  'image_filter_sharpen',
  'image_filter_transparency',
  'image_filter_webp_quality',
  'xslt_stylesheet',
  'xslt_types',
  'xslt_param',
  'xslt_string_param',
  'sub_filter',
  'sub_filter_once',
  'sub_filter_types',
  'add_after_body',
  'add_before_body',
  'add_types',
  'charset_map',
  'source_charset',
  'override_charset',
  'error_page',
  'post_action',
  'stub_status',
  'empty_gif',
  'flv',
  'mp4',
  'mp4_limit_rate',
  'mp4_limit_rate_after',
  'secure_link',
  'secure_link_md5',
  'secure_link_secret',
  'http2',
  'http2_push_preload',
  'http2_recv_timeout',
  'http2_idle_timeout',
  'http2_max_concurrent_streams',
  'http2_max_field_size',
  'http2_max_header_size',
  'http2_max_requests',
  'http2_recv_buffer_size',
  'http2_chunk_size',
  'http2_streams_index_size',
  'http2_streams_queue_size',
  'http2_max_frame_size',
  'http2_recv_window',
  'http2_send_window',
  'http2_push',
  'grpc_pass',
  'grpc_ssl',
  'grpc_ssl_certificate',
  'grpc_ssl_certificate_key',
  'grpc_ssl_protocols',
  'grpc_ssl_ciphers',
  'grpc_ssl_server_name',
  'grpc_ssl_verify',
  'grpc_ssl_verify_depth',
  'grpc_ssl_trusted_certificate',
  'grpc_ssl_crl',
  'grpc_buffer_size',
  'grpc_socket_keepalive',
  'grpc_connect_timeout',
  'grpc_send_timeout',
  'grpc_read_timeout',
  'grpc_intercept_errors',
  'grpc_ignore_headers',
  'grpc_set_header',
  'grpc_pass_header',
  'grpc_hide_header',
  'grpc_next_upstream',
  'grpc_next_upstream_tries',
  'grpc_next_upstream_timeout',
  'grpc_ssl_session_reuse',
  'grpc_ssl_name',
  'on',
  'off',
  'true',
  'false',
  'any',
  'all',
  'none',
  'http',
  'https',
  'default_server'
];

export const nginxLanguageDefinition: monaco.languages.IMonarchLanguage = {
  tokenizer: {
    root: [
      [/^#.*$/, 'comment'],
      [/\{|\}/, 'delimiter.bracket'],
      [/;$/, 'delimiter.semicolon'],
      [/\b(?:on|off|true|false)\b/, 'constant'],
      [/\b(?:http|https)\b/, 'keyword'],
      [/\b(?:listen|server_name|root|index|proxy_pass|proxy_set_header|location|server|upstream|events|include|worker_processes|worker_connections|error_log|access_log|client_max_body_size|try_files|alias|rewrite|return|if|set|add_header|expires|gzip|ssl|ssl_certificate|ssl_certificate_key|ssl_protocols|ssl_ciphers|fastcgi_pass|fastcgi_param|uwsgi_pass|uwsgi_param|scgi_pass|memcached_pass|limit_req|limit_conn|deny|allow|auth_basic|log_format|types|default_type|charset|keepalive_timeout|sendfile|tcp_nopush|tcp_nodelay|client_body_buffer_size|client_max_body_size|proxy_cache|proxy_cache_path|proxy_cache_key|proxy_cache_valid|proxy_cache_bypass|proxy_no_cache|proxy_connect_timeout|proxy_send_timeout|proxy_read_timeout|proxy_buffering|proxy_redirect|proxy_http_version|proxy_ssl_server_name|proxy_ssl_protocols|proxy_ssl_ciphers|proxy_ssl_verify|proxy_ssl_verify_depth|proxy_ssl_trusted_certificate|proxy_ssl_certificate|proxy_ssl_certificate_key|proxy_ssl_session_reuse|proxy_ssl_name|proxy_ssl_crl|proxy_intercept_errors|proxy_next_upstream|proxy_next_upstream_tries|proxy_next_upstream_timeout|proxy_hide_header|proxy_pass_header|proxy_ignore_headers|proxy_set_body|proxy_method|proxy_cookie_domain|proxy_cookie_path|proxy_force_ranges|proxy_limit_rate|proxy_request_buffering|proxy_socket_keepalive|proxy_timeout|proxy_bind|fastcgi_index|fastcgi_cache|fastcgi_cache_path|fastcgi_cache_key|fastcgi_cache_valid|fastcgi_cache_bypass|fastcgi_no_cache|fastcgi_hide_header|fastcgi_pass_header|fastcgi_ignore_headers|fastcgi_connect_timeout|fastcgi_send_timeout|fastcgi_read_timeout|fastcgi_buffer_size|fastcgi_buffers|fastcgi_busy_buffers_size|fastcgi_temp_file_write_size|fastcgi_intercept_errors|uwsgi_cache|uwsgi_cache_path|uwsgi_cache_key|uwsgi_cache_valid|uwsgi_cache_bypass|uwsgi_no_cache|uwsgi_connect_timeout|uwsgi_send_timeout|uwsgi_read_timeout|uwsgi_buffer_size|uwsgi_buffers|uwsgi_busy_buffers_size|uwsgi_temp_file_write_size|uwsgi_intercept_errors|scgi_param|memcached_connect_timeout|memcached_send_timeout|memcached_read_timeout|memcached_buffer_size|memcached_next_upstream|gzip_vary|gzip_proxied|gzip_comp_level|gzip_types|gzip_disable|gzip_min_length|gzip_buffers|gzip_http_version|ssl_prefer_server_ciphers|ssl_session_cache|ssl_session_timeout|ssl_session_tickets|ssl_stapling|ssl_stapling_verify|ssl_trusted_certificate|ssl_client_certificate|ssl_verify_client|ssl_verify_depth|ssl_crl|ssl_dhparam|internal|break|last|redirect|permanent|default_type|charset_types|worker_rlimit_nofile|worker_rlimit_sigpending|worker_shutdown_timeout|multi_accept|use|daemon|master_process|pid|debug_connection|env|timer_resolution|working_directory|user|group|pcre_jit|thread_pool|thread_pool_size|aio|aio_write|directio|directio_alignment|sendfile_max_chunk|reset_timedout_connection|keepalive_requests|lingering_time|lingering_timeout|satisfy|satisfy_any|auth_basic_user_file|auth_request|auth_request_set|limit_except|limit_rate|limit_rate_after|limit_req_zone|limit_req_status|limit_conn_zone|limit_conn_status|log_not_found|log_subrequest|open_log_file_cache|open_file_cache|open_file_cache_valid|open_file_cache_min_uses|open_file_cache_errors|recursive_error_pages|server_tokens|server_name_in_redirect|port_in_redirect|msie_padding|msie_refresh|absolute_redirect|ignore_invalid_headers|merge_slashes|underscores_in_headers|variables_hash_bucket_size|variables_hash_max_size|types_hash_bucket_size|types_hash_max_size|server_names_hash_bucket_size|server_names_hash_max_size|client_body_in_file_only|client_body_in_single_buffer|client_body_timeout|client_header_buffer_size|client_header_timeout|large_client_header_buffers|connection_pool_size|request_pool_size|postpone_output|send_timeout|subrequest_output_buffer_size|chunked_transfer_encoding|etag|if_modified_since|max_ranges|resolver|resolver_timeout|resolver_address|valid_referers|invalid_referers|referer_hash_max_size|referer_hash_bucket_size|real_ip_header|set_real_ip_from|real_ip_recursive|geo|geoip_country|geoip_city|geoip_org|geoip_proxy|geoip_proxy_recursive|map|map_hash_bucket_size|map_hash_max_size|split_clients|perl|perl_modules|perl_require|perl_set|image_filter|image_filter_buffer|image_filter_jpeg_quality|image_filter_sharpen|image_filter_transparency|image_filter_webp_quality|xslt_stylesheet|xslt_types|xslt_param|xslt_string_param|sub_filter|sub_filter_once|sub_filter_types|add_after_body|add_before_body|add_types|charset_map|source_charset|override_charset|error_page|post_action|stub_status|empty_gif|flv|mp4|mp4_limit_rate|mp4_limit_rate_after|secure_link|secure_link_md5|secure_link_secret|http2|http2_push_preload|http2_recv_timeout|http2_idle_timeout|http2_max_concurrent_streams|http2_max_field_size|http2_max_header_size|http2_max_requests|http2_recv_buffer_size|http2_chunk_size|http2_streams_index_size|http2_streams_queue_size|http2_max_frame_size|http2_recv_window|http2_send_window|http2_push|grpc_ssl|grpc_ssl_certificate|grpc_ssl_certificate_key|grpc_ssl_protocols|grpc_ssl_ciphers|grpc_ssl_server_name|grpc_ssl_verify|grpc_ssl_verify_depth|grpc_ssl_trusted_certificate|grpc_ssl_crl|grpc_buffer_size|grpc_socket_keepalive|grpc_connect_timeout|grpc_send_timeout|grpc_read_timeout|grpc_intercept_errors|grpc_ignore_headers|grpc_set_header|grpc_pass_header|grpc_hide_header|grpc_next_upstream|grpc_next_upstream_tries|grpc_next_upstream_timeout|grpc_ssl_session_reuse|grpc_ssl_name|default_server)\b/, 'keyword'],
      [/\b(?:\d+\.?\d*(?:[KMG]i?b?)?)\b/, 'number'],
      [/\$[a-zA-Z_][a-zA-Z0-9_]*/, 'variable.predefined'],
      [/"([^"\\]|\\.)*"/, 'string'],
      [/'([^'\\]|\\.)*'/, 'string'],
      [/[a-zA-Z_-][a-zA-Z0-9_-]*/, 'identifier']
    ]
  }
};

export function registerNginxLanguage() {
  monaco.languages.register({ id: 'nginx' });
  monaco.languages.setLanguageConfiguration('nginx', nginxLanguageConfiguration);
  monaco.languages.setMonarchTokensProvider('nginx', nginxLanguageDefinition);
}
